# numpyの行列操作
[参照、抽出、結合](https://qiita.com/supersaiakujin/items/d63c73bb7b5aac43898a#%E4%BA%8C%E6%AC%A1%E5%85%83%E3%81%AE%E5%A0%B4%E5%90%88)

In [1]:
import numpy as np

## 行列の定義

In [19]:
#手打ち
test=np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15]])

In [20]:
test

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [25]:
#reshapeを使う
test=np.arange(20).reshape(4,5)

In [26]:
test

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [3]:
#数列の一般項を与えるイメージ
test=np.array([x**2 for x in range(100)])
test

array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
       1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916,
       3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225,
       4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776,
       5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569,
       7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604,
       9801])

## 要素の抽出

In [27]:
test[1,1]

6

## 行、列の抽出

In [28]:
test[0,:]

array([0, 1, 2, 3, 4])

In [29]:
test[1:3,1:4:2]

array([[ 6,  8],
       [11, 13]])

## 要素の抽出（indexにlistを渡す場合）

In [31]:
#listは同じ長さ
test[[0,2],[0,2]]

array([ 0, 12])

## 行列の抽出（index指定）

In [32]:
test[np.ix_([0,2],[0,2])]

array([[ 0,  2],
       [10, 12]])

# 行列を用いた計算

## 要素毎の積

In [4]:
A = np.ones((3,3))
A

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [6]:
B = 3 * np.ones((3,3))
B

array([[ 3.,  3.,  3.],
       [ 3.,  3.,  3.],
       [ 3.,  3.,  3.]])

In [7]:
A * B

array([[ 3.,  3.,  3.],
       [ 3.,  3.,  3.],
       [ 3.,  3.,  3.]])

In [8]:
# * と結果は同じ
np.multiply(A, B)

array([[ 3.,  3.,  3.],
       [ 3.,  3.,  3.],
       [ 3.,  3.,  3.]])

## 行列積

In [9]:
np.dot(A, B)

array([[ 9.,  9.,  9.],
       [ 9.,  9.,  9.],
       [ 9.,  9.,  9.]])

## 演算

In [12]:
#軸指定無しは全ての和
np.sum(A)

9.0

In [14]:
# 行方向に走る和 次元に注意
np.sum(A, axis = 0)

array([ 3.,  3.,  3.])

In [15]:
# 行方向に走る和 次元保存
np.sum(A, axis = 0, keepdims=True)

array([[ 3.,  3.,  3.]])

In [16]:
# 列方向に走る和 次元保存
np.sum(A, axis = 1, keepdims=True)

array([[ 3.],
       [ 3.],
       [ 3.]])

In [18]:
#次元の削減
C = np.sum(A, axis = 1, keepdims=True)
print(C)
C = np.squeeze(C)
print(C)

[[ 3.]
 [ 3.]
 [ 3.]]
[ 3.  3.  3.]


## 閾値

In [19]:
test=np.array([[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15]])

In [20]:
test

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [21]:
test < 5

array([[ True,  True,  True,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False]], dtype=bool)